addr="127.0.0.1:6389"

#log_path: /Users/flike/src 
#日志级别
logLevel="debug"

#递增id的 bucket步长
bucketStep=10

#持久化方式 1:mysql , 2:文件持久化
persistType=2

#文件持久化存储路径 , 默认当前data目录下
dataDir="."

#db持久化是否使用事务
useTransAction=true

[mysql]
host="127.0.0.1"
port=3306
user="root"
password="cclehui06156041"
name="test"
maxIdleConns=4
maxOpenConns=20
