addr="127.0.0.1:6389"

#log_path: /Users/flike/src 
#日志级别
logLevel="debug"

#递增id的 bucket步长 增大步长可以有效减少持久化机会提高性能
bucketStep=10

#server_type  master 还是 slave
serverType="master"

# master 数据同步的 ip和端口
masterAddress="localhost:9000"

#master slave 连接不活跃的时间 单位秒
maxUnActiveTs=10

#持久化方式 1:mysql , 2:文件持久化(boltdb)
persistType=2

#文件持久化存储路径 , 默认当前data目录下
dataDir="."

#db持久化是否使用事务
useTransAction=true

[bolt]
filePath="./data/bolt_kv.db"
bucketName="idGenerator"

[mysql]
host="127.0.0.1"
port=3306
user="root"
password="cclehui06156041"
name="test"
maxIdleConns=4
maxOpenConns=20
