addr="127.0.0.1:6389"

#log_path: /Users/flike/src 
#日志级别
logLevel="debug"

#递增id的 bucket步长
bucketStep=1000

#db持久化是否使用事务
useTransAction=true

[mysql]
host="127.0.0.1"
port=3306
user="root"
password="cclehui06156041"
name="test"
maxIdleConns=4
maxOpenConns=20
